data:
  window:
    start: "2013-01-02"
    end: "2017-12-29"
  feature_horizon: 30  # Increased window to capture more temporal patterns
graph:
  corr_threshold: null  # Using top_k instead of threshold
  top_k: 20  # Increase connections per node
  use_mst: true  # force connectivity with minimum spanning tree
model:
  type: "gcn"  # | "gat"
  hidden_dim: 64
  dropout: 0.2
  gat_heads: 8
  gat_dim_per_head: 8
train:
  epochs: 300
  batch_size: 1  # full-batch graph learning
  lr: 5e-4  # Lower learning rate for better stability
  weight_decay: 1e-4  # Increased regularization
  early_stop_patience: 30  # More patience for finding optimal weights
  random_seed: 42
