data:
  window:
    start: "2013-01-02"
    end: "2017-12-29"
  feature_horizon: 30  # Increased window to capture more temporal patterns
graph:
  corr_threshold: null  # Using top_k instead of threshold
  top_k: 20  # Increase connections per node
  use_mst: true  # force connectivity with minimum spanning tree
  # Dynamic graph parameters
  mode: "static"  # | "dynamic" | "dual"
  window_size: 60    # Number of trading days per graph snapshot
  step_size: 5      # Number of days to slide between snapshots
model:
  type: "gcn"  # | "gat"
  hidden_dim: 16  # Drastically reduce model capacity
  dropout: 0.5  # Heavy dropout
  gat_heads: 8
  gat_dim_per_head: 8
train:
  epochs: 200   # More epochs with smaller learning rate
  batch_size: 1  # full-batch graph learning
  lr: 5e-4      # Smaller learning rate for financial time series
  weight_decay: 1e-4  # Slightly reduced regularization with smaller learning rate
  early_stop_patience: 20  # More patience with slower learning
  random_seed: 42
time_aware_training:
  enabled: true
  # Use rolling window training - critical for financial time series!
  window_size: 60    # Train on 60 trading days (~3 months)
  stride: 20        # Shift window by 20 days between training rounds
  future_gap: 5      # Ensure 5 days between train and validation
